In [33]:
from tensorflow.keras.datasets import mnist


In [34]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


In [35]:
train_images #each is 28*28 means 2d then since they are uopn each other they are overall grouped as one making it 3d

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [36]:
len(train_images)

60000

In [37]:
train_images[0]   #this is the first image array as u see its 2d

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [38]:
train_images[0].shape #shape

(28, 28)

In [39]:
len(test_images)

10000

In [40]:
train_labels #class i.e output for each image given like for first image it is given for training that it is image of 5 and same goes on as these r 60000 labels for 60000 images

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [41]:
len(train_labels)

60000

In [42]:
#now starting model training
from tensorflow.keras import models
from tensorflow.keras import layers

In [43]:
network=models.Sequential()  #making sequential type object from model
#in this seq model the layer is one after another

In [44]:
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
#we are adding a dense type layers
# In dense(first parameter is no of nodes we want in first layer(after input layer) 512 is arbitary but usually we put in order 2^power in decreasing order
# here we have put 512 as book reseon being bcz the shape of input is 28*28 or u can give 784 in arguemnt as well as well which means 784 nodes, each node for one pixel, 
# and as the the nodes of inp layer would be 784 the first layer has then nearest lower 2^power node that is 512 )


In [45]:
network.add(layers.Dense(10, activation='softmax'))
#this is second layer of 10 nodes , now we don't have to give the shape as output of previous layers are automatically maaped as input for next layers
#since this layer is last layer so it is output layer, now ten nodes will predict the probability score(softmax gives prob)  among ten probabilities(each for 0 to 9 digits)
# the one whose probability will be more (it will be like 0.1,0.4,0.2.... (from total of 1)) ,we can say this is the digit predicted

In [46]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])
#now network is ready

In [47]:
#preprocessing dataw
# we will have to conver6t the data in the form as our network expects;
# here our network expects vector(1d) while our data is in 3d (images r 2d) after stacking 60000 depth is added hence 3d,it had shape (60000,28,28) that is 3d as 60000 is depth 28 28 is h n w

# so we will reshape it here in 1d means 1d images with 60000 depth data is 2d
# it will take one 28*28 image, put its 28 rows in the new matrix horizonatally one by one so each having 28 col will show like 784 col in new matrix ,(each row for each image) means 60000 rows and 784 col (60000,784) will be new shape
# secondly values are ranging in b/w [0,255]  so it will fluctuating very much for the model to learn such values tho still model can learn but it will have to face dificulty
# so we divide all the values with highest one that is 255 here so now values wl be ranging in between [0,1]


In [48]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255


In [49]:
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
#converting  nominal labels into categories here by using to_categorical func of keras via one hot encoding

In [50]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)
#60000/128=469 means we said give a batch of 128 images,it requires 469 iterations to give 60000 images to model, 469*128=60000(it picks randomly)
#batch size effects time complexity,it should be normal
#whenever u chnge epochs then do start from the object creation of model again,otherwise it will start from last accuracy
#incase u want latter case then u can


Epoch 1/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2554 - accuracy: 0.9269
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1040 - accuracy: 0.9690
Epoch 3/5
469/469 [==============================] - 4s 10ms/step - loss: 0.0682 - accuracy: 0.9795
Epoch 4/5
469/469 [==============================] - 4s 10ms/step - loss: 0.0502 - accuracy: 0.9850
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0379 - accuracy: 0.9885


In [51]:
network.evaluate(test_images,test_labels)
#we can see in training the accuracy was 0.9885 but in testing it is 0.9812 , the differnce between tarined and test result is called overfiting

313/313 [==============================] - 1s 3ms/step - loss: 0.0626 - accuracy: 0.9812


[0.06264331936836243, 0.9811999797821045]